<nav class="admin-navigation">
	<h2 class="left-border-heading">Opcje administratora</h2>
	<ul class="admin-panel-menu">
		<li class="admin-panel-menu__item admin-panel-menu__item--main"><a href="admin_panel.php">Panel główny</a></li>
		<li class="admin-panel-menu__item"><a href="admin_groups.php">Grupy i uprawnienia</a></li>
		<li class="admin-panel-menu__item"><a href="admin_sections.php">Działy</a></li>
		<li class="admin-panel-menu__item"><a href="admin_categories.php">Kategorie</a></li>
		<li class="admin-panel-menu__item"><a href="admin_bans.php">Bany</a></li>
		<li class="admin-panel-menu__item"><a href="admin_decorations.php">Odznaczenia</a></li>
		<li class="admin-panel-menu__item"><a href="admin_jutsu.php">Jutsu</a></li>
		<li class="admin-panel-menu__item"><a href="admin_items.php">Przedmioty</a></li>
		<li class="admin-panel-menu__item"><a href="admin_skills.php">Umiejętności</a></li>
		<li class="admin-panel-menu__item"><a href="admin_summons.php">Summony</a></li>
		<li class="admin-panel-menu__item"><a href="admin_rewards.php">Wynagrodzenia dla graczy</a></li>
	</ul>
</nav>