<footer class="footer footer--main footer__wrapper">
	<div class="footer__copyright">
		<img src="style/img/favicon.ico">
		<p>Wszelkie prawa zastrzeżone przez:<br><a href="forum.php">Ninja Clan Wars</a> 2009-<?php echo date("Y");?></p>
	</div>

	<div class="footer__socials">
		<a href="https://www.facebook.com/NinjaClanWars/"><i class="footer__icon footer__icon--fb icon-facebook"></i></a>
		<a href="https://www.youtube.com/channel/UCOKcQFjL5H2_3DBm6qCYydg"><i class="footer__icon footer__icon--yt icon-youtube-play"></i></a>
	</div>
</footer>