<!-- META -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="theme-color" content="#0b4a77">
<link rel="icon" sizes="50x50" href="style/img/favicon.ico">
<meta property="og:url" content="http://www.ninjaclanwars.pl">
<meta property="og:type" content="website">
<meta property="og:title" content="Ninja Clan Wars">
<meta property="og:description" content="Ninja Clan Wars - przeglądarkowa gra Naruto play by forum!">
<meta property="og:image" content="style/img/logo.png">

<!-- CSS -->
<link rel="stylesheet" type="text/css" href="style/reset.css">
<link rel="stylesheet" type="text/css" href="style/style.min.css">
<link rel="stylesheet" type="text/css" href="style/fontello.css">

<!-- CSS FONTS -->
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Signika+Negative"> <!-- czcionka główna -->
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Titillium+Web&subset=latin,latin-ext"> <!-- czcionka do działów krain -->
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Bangers&subset=latin,latin-ext"> <!-- czcionka do kafelek -->
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900"> <!-- czcionka do postów -->

<!-- JS -->
<script src="https://code.jquery.com/jquery-3.2.1.js"></script>
<script defer src="js/mobileMenu.js"></script>
<script defer src="js/animations.js"></script>
<script defer src="js/bbcodeMenuV2.js"></script>
<script defer src="js/jquery.sticky.js"></script>

<script>
  $(document).ready(function(){
    $(".menu").sticky({topSpacing:0});
  });
</script>
