<nav class="mobile-nav">
	<ul class="mobile-nav__menu">
		<li class="mobile-nav__item"><a href="#" data-click="land_switcher"><i class="mobile-nav__icon icon-switch"></i>Switcher</a></li>
		<li class="mobile-nav__item"><a href="maps.php"><i class="mobile-nav__icon icon-globe"></i>Mapy</a></li>
		<li class="mobile-nav__item"><a href="forum.php"><i class="mobile-nav__icon icon-home"></i>Główna</a></li>
		<li class="mobile-nav__item"><a href="#" data-click="menu"><i class="mobile-nav__icon icon-menu"></i>Menu</a></li>
	</ul>
</nav>
